"""empty message

Revision ID: 6ef63fc723da
Revises: 54717577e125
Create Date: 2019-09-04 13:40:43.794982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ef63fc723da'
down_revision = '54717577e125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name', sa.String(length=50), nullable=True))
    op.drop_index('role_name', table_name='role')
    op.create_unique_constraint(None, 'role', ['name'])
    op.drop_column('role', 'role_name')
    op.add_column('user', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.drop_index('ix_user_user_name', table_name='user')
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
    op.create_index('ix_user_user_name', 'user', ['user_name'], unique=True)
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'name')
    op.add_column('role', sa.Column('role_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_constraint(None, 'role', type_='unique')
    op.create_index('role_name', 'role', ['role_name'], unique=True)
    op.drop_column('role', 'name')
    # ### end Alembic commands ###
